services:
  - type: web
    name: wesavefood
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    autoDeploy: true 